# Generated by Django 3.1.7 on 2022-11-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='donation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
