# Generated by Django 3.1.7 on 2022-11-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20221127_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='donation_percent',
            field=models.CharField(default='5%', max_length=100),
        ),
    ]
