# Generated by Django 3.1.7 on 2022-11-27 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('stock', models.IntegerField(default=0)),
                ('in_stock', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=True)),
                ('small_in_stock', models.BooleanField(default=True)),
                ('small_stock', models.IntegerField(default=0)),
                ('small_price', models.DecimalField(decimal_places=2, default=4, max_digits=4)),
                ('mini_in_stock', models.BooleanField(default=True)),
                ('mini_stock', models.IntegerField(default=0)),
                ('mini_price', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='ecommerce.category')),
            ],
            options={
                'verbose_name_plural': 'products',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True)),
                ('rating', models.IntegerField(default=5)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='reviews/')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='ecommerce.product')),
            ],
            options={
                'verbose_name_plural': 'reviews',
                'ordering': ('-date',),
            },
        ),
    ]
