# Generated by Django 3.1.7 on 2022-11-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='/', upload_to='images/'),
        ),
    ]
