# Generated by Django 4.1.3 on 2023-01-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.IntegerField(max_length=8)),
                ('enquiry', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='enquiries/')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'enquiries',
                'ordering': ('-date',),
            },
        ),
    ]
