# Generated by Django 4.1.3 on 2023-01-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_enquiry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
