# Generated by Django 4.1.3 on 2023-01-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_enquiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
