# Generated by Django 4.1.3 on 2023-01-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_enquiry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='enquiries/'),
        ),
    ]
