# Generated by Django 4.1.3 on 2023-01-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_enquiry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(default=0, max_length=8),
        ),
    ]
