# Generated by Django 3.1.7 on 2022-11-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dateby',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
