# Generated by Django 3.1.7 on 2022-11-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_dateby'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='charity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('PayNow/PayLah', 'paynow'), ('Cash', 'cash')], default='paynow', max_length=100),
        ),
    ]
