# Generated by Django 3.1.7 on 2022-11-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20221127_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='donation_percent',
            field=models.CharField(choices=[('5%', '5'), ('10%', '10'), ('15%', '15'), ('20%', '20'), ('Custom', 'custom'), ('None', 'none')], default='5', max_length=100),
        ),
    ]
