# Generated by Django 3.1.7 on 2022-11-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_donation_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='donation_percent',
            field=models.CharField(choices=[('5', '5%'), ('10', '10%'), ('15', '15%'), ('20', '20%'), ('custom', 'Custom'), ('none', 'None')], default='5', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paynow', 'PayNow/PayLah'), ('cash', 'Cash')], default='paynow', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('delivery', 'Delivery with NinjaVan'), ('self-collect', 'Self-collection')], default='delivery', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('scheduled', 'Scheduled'), ('shipped', 'Shipped'), ('processing', 'Processing')], default='processing', max_length=100),
        ),
    ]
